{{- if .Values.image.credentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
