{{ if .Values.persistentVolumeClaims }}
{{- range .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    app: {{ include "chart.name" $ }}
    chart: {{ include "chart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    version: {{ $.Chart.Version }}
spec:
  accessModes:
  - {{ .accessMode }}
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
